<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Agent.Abstractions\Agent.Abstractions.csproj" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.67.1" />
  </ItemGroup>
</Project>
